import './globals.css';
import RecoilRootProvider from '../util/recoilRootProvider';

export const metadata = {
  title: 'OTTE',
  description: 'Generated by create i5j5',
  appleWebApp: {
    statusBarStyle: 'black-translucent',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body suppressHydrationWarning={true}>
        <RecoilRootProvider>{children}</RecoilRootProvider>
      </body>
    </html>
  );
}
