import './globals.css';

export const metadata = {
  title: 'OTTE',
  description: 'Generated by create i5j5',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body suppressHydrationWarning={true}>{children}</body>
    </html>
  );
}
